  `REC_ID` int(11) NOT NULL auto_increment,
  `MATCHCODE` varchar(255) NOT NULL default '',
  `KUNDENGRUPPE` int(11) NOT NULL default '0',
  `SPRACH_ID` int(11) NOT NULL default '2',
  `GESCHLECHT` char(1) NOT NULL default '-',
  `KUNNUM1` varchar(20) default NULL,
  `KUNNUM2` varchar(20) default NULL,
  `NAME1` varchar(40) default NULL,
  `PLZ` varchar(10) default NULL,
  `ORT` varchar(40) default NULL,
  `LAND` varchar(5) default NULL,
  `NAME2` varchar(40) default NULL,
  `NAME3` varchar(40) default NULL,
  `ABTEILUNG` varchar(40) default NULL,
  `ANREDE` varchar(40) default NULL,
  `STRASSE` varchar(40) default NULL,
  `POSTFACH` varchar(40) default NULL,
  `PF_PLZ` varchar(10) default NULL,
  `DEFAULT_LIEFANSCHRIFT_ID` int(11) NOT NULL default '-1',
  `GRUPPE` varchar(4) default NULL,
  `TELE1` varchar(100) default NULL,
  `TELE2` varchar(100) default NULL,
  `FAX` varchar(100) default NULL,
  `FUNK` varchar(100) default NULL,
  `EMAIL` varchar(100) default NULL,
  `EMAIL2` varchar(100) default NULL,
  `INTERNET` varchar(100) default NULL,
  `DIVERSES` varchar(100) default NULL,
  `BRIEFANREDE` varchar(100) default NULL,
  `BLZ` varchar(20) default NULL,
  `KTO` varchar(20) default NULL,
  `BANK` varchar(40) default NULL,
  `IBAN` varchar(100) default NULL,
  `SWIFT` varchar(100) default NULL,
  `KTO_INHABER` varchar(40) default NULL,
  `DEB_NUM` int(11) default NULL,
  `KRD_NUM` int(11) default NULL,
  `STATUS` int(11) default NULL,
  `NET_SKONTO` decimal(5,2) default NULL,
  `NET_TAGE` tinyint(4) default NULL,
  `BRT_TAGE` tinyint(4) default NULL,
  `WAEHRUNG` varchar(5) NOT NULL default '',
  `UST_NUM` varchar(25) default NULL,
  `VERTRETER_ID` int(11) unsigned NOT NULL default '0',
  `PROVIS_PROZ` decimal(5,2) NOT NULL default '0.00',
  `INFO` text,
  `GRABATT` decimal(5,2) default NULL,
  `KUN_KRDLIMIT` decimal(10,2) default NULL,
  `KUN_LIEFART` int(11) NOT NULL default '-1',
  `KUN_ZAHLART` int(11) NOT NULL default '-1',
  `KUN_PRLISTE` enum('N','Y') NOT NULL default 'N',
  `KUN_LIEFSPERRE` enum('N','Y') NOT NULL default 'N',
  `LIEF_LIEFART` int(11) NOT NULL default '-1',
  `LIEF_ZAHLART` int(11) NOT NULL default '-1',
  `LIEF_PRLISTE` enum('N','Y') NOT NULL default 'N',
  `LIEF_TKOSTEN` decimal(10,2) NOT NULL default '0.00',
  `LIEF_MBWERT` decimal(10,2) NOT NULL default '0.00',
  `PR_EBENE` tinyint(1) default '5',
  `BRUTTO_FLAG` enum('N','Y') NOT NULL default 'N',
  `MWST_FREI_FLAG` enum('N','Y') NOT NULL default 'N',
  `KUNPREIS_AUTO` enum('N','Y') NOT NULL default 'N',
  `KUN_SEIT` date default NULL,
  `KUN_GEBDATUM` date default NULL,
  `ENTFERNUNG` int(10) unsigned default NULL,
  `ERSTELLT` date default NULL,
  `ERST_NAME` varchar(20) default NULL,
  `GEAEND` date default NULL,
  `GEAEND_NAME` varchar(20) default NULL,
  `SHOP_KUNDE` enum('N','Y') NOT NULL default 'N',
  `SHOP_ID` tinyint(3) NOT NULL default '-1',
  `SHOP_NEWSLETTER` enum('N','Y') NOT NULL default 'N',
  `SHOP_KUNDE_ID` int(11) NOT NULL default '-1',
  `SHOP_CHANGE_FLAG` tinyint(1) unsigned NOT NULL default '0',
  `SHOP_DEL_FLAG` enum('N','Y') NOT NULL default 'N',
  `SHOP_PASSWORD` varchar(20) default NULL,
  `USERFELD_01` varchar(255) default NULL,
  `USERFELD_02` varchar(255) default NULL,
  `USERFELD_03` varchar(255) default NULL,
  `USERFELD_04` varchar(255) default NULL,
  `USERFELD_05` varchar(255) default NULL,
  `USERFELD_06` varchar(255) default NULL,
  `USERFELD_07` varchar(255) default NULL,
  `USERFELD_08` varchar(255) default NULL,
  `USERFELD_09` varchar(255) default NULL,
  `USERFELD_10` varchar(255) default NULL,
  PRIMARY KEY  (`REC_ID`),
  KEY `IDX_KUNNUM1` (`KUNNUM1`),
  KEY `IDX_MATCH` (`MATCHCODE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

# Data exporting was unselected.
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
