111011 15:17:41	      5 Query       SHOW COLUMNS FROM ADRESSEN
		      5 Query       SHOW INDEX FROM ADRESSEN
		      5 Query       select ADRESSEN.* FROM ADRESSEN WHERE KUNDENGRUPPE=1 ORDER BY MATCHCODE LIMIT 0,50