id char(36) NOT NULL,
name varchar(150) DEFAULT NULL,
date_entered datetime DEFAULT NULL,
date_modified datetime DEFAULT NULL,
modified_user_id char(36) DEFAULT NULL,
created_by char36) DEFAULT NULL,
description text
deleted tinyint1) DEFAULT '0',
assigned_user_id char(36) DEFAULT NULL,
account_type varchar(50) DEFAULT NULL,
industry varchar(50) DEFAULT NULL,
annual_revenue varchar(100) DEFAULT NULL,
phone_fax varchar(100) DEFAULT NULL,
billing_address_street varchar(150) DEFAULT NULL,
billing_address_city varchar(100) DEFAULT NULL,
billing_address_state varchar(100) DEFAULT NULL,
billing_address_postalcode varchar(20) DEFAULT NULL,
billing_address_country varchar(255) DEFAULT NULL,
rating varchar(100) DEFAULT NULL,
phone_office varchar(100) DEFAULT NULL,
phone_alternate varchar(100) DEFAULT NULL,
website varchar(255) DEFAULT NULL,
ownership varchar(100) DEFAULT NULL,
employees varchar(10) DEFAULT NULL,
ticker_symbol varchar(10) DEFAULT NULL,
shipping_address_street varchar(150) DEFAULT NULL,
shipping_address_city varchar(100) DEFAULT NULL,
shipping_address_state varchar(100) DEFAULT NULL,
shipping_address_postalcode varchar(20) DEFAULT NULL,
shipping_address_country varchar(255) DEFAULT NULL,
parent_id char(36) DEFAULT NULL,
sic_code varchar(10) DEFAULT NULL,
campaign_id char(36) DEFAULT NULL,


